<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Ajax extends CI_Controller
{

    function __construct()
    {
        parent::__construct();
        // is_login();
        $this->load->model('Ajax_model');
    }

    public function get_system_by_proj($id){
        $hasil = $this->Ajax_model->get_system_by_proj($id);
        echo json_encode($hasil);
    }

    public function get_discipline_by_proj($id){
        $hasil = $this->Ajax_model->get_discipline_by_proj($id);
        echo json_encode($hasil);
    }

    public function get_items_by_proj_AND_disc($id_d, $id_p){
        $where = array(
            'id_disciplines' => $id_d,
            'id_projects' => $id_p
        );
        $hasil = $this->Ajax_model->get_items_by_proj_AND_disc($where);
        echo json_encode($hasil);
    }

    public function get_items_by_proj($id_p){
        $hasil = $this->Ajax_model->get_items_by_proj($id_p);
        echo json_encode($hasil);
    }

    public function get_subsystem_by_proj_AND_sys($id_s, $id_p){
        $where = array(
            'id_systems' => $id_s,
            'id_projects' => $id_p
        );
        $hasil = $this->Ajax_model->get_subsystem_by_proj_AND_sys($where);
        echo json_encode($hasil);
    }

    public function get_templ_by_disc_AND_type(){
        $where = array(
            'id_disciplines' => $this->input->post('id_d'),
            'template_type' => $this->input->post('t_type')
        );
        $hasil = $this->Ajax_model->get_templ_by_disc_AND_type($where);
        echo json_encode($hasil);
    }
}

/* End of file Associates.php */
/* Location: ./application/controllers/Associates.php */
/* Please DO NOT modify this information : */
/* Generated by Denzoe Codeigniter CRUD Generator 2020-01-21 14:14:14 */
/* http://AA-soft develover.com */