<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Disciplines_model extends CI_Model
{

    public $table = 'tbl_disciplines';
    public $id = 'id_discipline';
    public $desc = 'DESC';
    public $asc = 'ASC';
    


    function __construct()
        {
            parent::__construct();
        }


    function get_all($status = 0)
        {
            $this->db->order_by($this->id, $this->desc);

            $this->db->select ('tbl_disciplines.*,
                                tbl_projects.project_name,
                                tbl_projects.project_status 
                              ');

            $this->db->where ('tbl_disciplines.discipline_status', $status);
            $this->db->where ('tbl_projects.project_status', $status);
            $this->db->from ('tbl_disciplines');
            $this->db->join ('tbl_projects', 'tbl_disciplines.id_projects = tbl_projects.id_project');

            return $this->db->get()->result();
        }
    
    function total_rows($q = NULL, $status = NULL) 
        {
            $this->db->group_start();
            $this->db->like ('tbl_disciplines.id_discipline', $q);
            $this->db->or_like ('tbl_projects.id_project', $q);
            $this->db->or_like ('tbl_disciplines.discipline_id', $q);
            $this->db->or_like ('tbl_disciplines.discipline_name', $q);
            $this->db->group_end();

            $this->db->select('tbl_disciplines.*');
            $this->db->where('tbl_disciplines.discipline_status', $status);
            $this->db->from('tbl_disciplines');
            return $this->db->count_all_results();
        }

    function get_limit_data($limit, $start = 0, $q = NULL, $status = NULL) 
        {
            $this->db->order_by($this->id, $this->desc);

            $this->db->group_start();
            $this->db->like(''.$this->table.'.id', $q);
            $this->db->or_like(''.$this->table.'.discipline_id', $q);
            $this->db->or_like(''.$this->table.'.discipline_name', $q);
            $this->db->group_end();

            $this->db->select(''.$this->table.'.*');
            $this->db->where(''.$this->table.'.discipline_status', $status);
            $this->db->from($this->table);
            $this->db->limit($limit, $start);
            return $this->db->get()->result();
        }

    /*function get_by_id($id)
        {
            $this->db->where($this->id, $id);
            return $this->db->get($this->table)->row();
        }

    function insert($data)
        {
            $this->db->insert($this->table, $data);
        }

    function update($id, $data)
        {
            $this->db->where($this->id, $id);
            $this->db->update($this->table, $data);
        }

    function delete($id)
        {
            $data = array('discipline_status' => 1,);
            $this->db->where($this->id, $id);
            $this->db->update($this->table,$data);
        }*/

}

/* End of file Disciplines_model.php */
/* Location: ./application/models/Disciplines_model.php */
/* Please DO NOT modify this information : */
/* Generated by Denzoe Codeigniter CRUD Generator 2019-12-28 01:54:37 */
/* http://AA-soft develover.com */