<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Items_model extends CI_Model
{

    public $table = 'tbl_items';
    public $id = 'id_item';
    public $desc = 'DESC';
    public $asc = 'ASC';
    


    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->desc);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        $this->db->join('tbl_disciplines', 'tbl_items.id_disciplines = tbl_disciplines.id_discipline');
        $this->db->join('tbl_projects', 'tbl_items.id_projects = tbl_projects.id_project');
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->where('project_status', 0);
        $this->db->where('discipline_status', 0);
        $this->db->group_start();           
        $this->db->like('id_item', $q);
    	$this->db->or_like('item_type_id', $q);
    	$this->db->or_like('id_disciplines', $q);
    	$this->db->or_like('item_type_id', $q);
    	$this->db->or_like('item_type_name', $q);
        $this->db->group_end();         
        $this->db->join('tbl_disciplines', 'tbl_items.id_disciplines = tbl_disciplines.id_discipline');
        $this->db->join('tbl_projects', 'tbl_items.id_projects = tbl_projects.id_project');
    	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->desc);
        $this->db->group_start();
        $this->db->like('id_item', $q);
        $this->db->or_like('item_type_id', $q);
        $this->db->or_like('id_disciplines', $q);
        $this->db->or_like('item_type_id', $q);
        $this->db->or_like('item_type_name', $q);
        $this->db->group_end();
        $this->db->where('project_status', 0);
        $this->db->where('discipline_status', 0);
        // MODIF BY FAZRI
        $this->db->join('tbl_disciplines', 'tbl_items.id_disciplines = tbl_disciplines.id_discipline');
        $this->db->join('tbl_projects', 'tbl_items.id_projects = tbl_projects.id_project');
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Items_model.php */
/* Location: ./application/models/Items_model.php */
/* Please DO NOT modify this information : */
/* Generated by Denzoe Codeigniter CRUD Generator 2020-01-06 12:27:42 */
/* http://AA-soft develover.com */