<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Perusahaan_model extends CI_Model
{

    public $table = 'tbl_perusahaan';
    public $id = 'id_perusahaan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_perusahaan', $q);
	$this->db->or_like('kode', $q);
	$this->db->or_like('nama_perusahaan', $q);
	$this->db->or_like('biodata', $q);
	$this->db->or_like('no_izin', $q);
	$this->db->or_like('no_hp', $q);
	$this->db->or_like('no_pajak', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('tgl_berdiri', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_perusahaan', $q);
	$this->db->or_like('kode', $q);
	$this->db->or_like('nama_perusahaan', $q);
	$this->db->or_like('biodata', $q);
	$this->db->or_like('no_izin', $q);
	$this->db->or_like('no_hp', $q);
	$this->db->or_like('no_pajak', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('tgl_berdiri', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Perusahaan_model.php */
/* Location: ./application/models/Perusahaan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Denzoe Codeigniter CRUD Generator 2019-10-06 10:17:06 */
/* http://AA-soft develover.com */