<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Projects_model extends CI_Model
{

    public $table = 'tbl_projects';
    public $id = 'id_projects';
    public $desc = 'DESC';
    public $asc = 'ASC';
    


    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all($status = NULL)
    {
        $this->db->order_by($this->id, $this->desc);
        $this->db->where('project_status',$status);
        $this->db->from($this->table);
        return $this->db->get()->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL ,$status = NULL) {
    $this->db->group_start();  
    $this->db->like('id_projects', $q);
	$this->db->or_like('project_id', $q);
	$this->db->or_like('project_name', $q);
	$this->db->or_like('project_desc', $q);
    $this->db->group_end(); 
    $this->db->where('project_status',$status);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL ,$status = NULL) {
        $this->db->order_by($this->id, $this->desc);
    $this->db->group_start();  
    $this->db->like('id_projects', $q);
	$this->db->or_like('project_id', $q);
	$this->db->or_like('project_name', $q);
	$this->db->or_like('project_desc', $q);
    $this->db->group_end();  
    $this->db->where('project_status',$status);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $data = array('project_status' => 1,);
        $this->db->where($this->id, $id);
        $this->db->update($this->table,$data);
    }

}

/* End of file Projects_model.php */
/* Location: ./application/models/Projects_model.php */
/* Please DO NOT modify this information : */
/* Generated by Denzoe Codeigniter CRUD Generator 2019-12-27 05:25:17 */
/* http://AA-soft develover.com */