<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Punchlist_model extends CI_Model
{

    public $table = 'tbl_punchlist';
    public $id = 'id';
    public $desc = 'DESC';
    public $asc = 'ASC';
    


    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->desc);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('punch_id', $q);
	$this->db->or_like('punch_location_no', $q);
	$this->db->or_like('punch_sub_no', $q);
	$this->db->or_like('punch_discipline_no', $q);
	$this->db->or_like('punch_itemNo', $q);
	$this->db->or_like('punch_desc', $q);
	$this->db->or_like('punch_category', $q);
	$this->db->or_like('originator_ctr', $q);
	$this->db->or_like('originator_cpy', $q);
	$this->db->or_like('originator_date', $q);
	$this->db->or_like('verified_ctr', $q);
	$this->db->or_like('verified_cpy', $q);
	$this->db->or_like('verified_date', $q);
	$this->db->or_like('punch_status', $q);
	$this->db->or_like('punch_date', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->desc);
        $this->db->like('id', $q);
	$this->db->or_like('punch_id', $q);
	$this->db->or_like('punch_location_no', $q);
	$this->db->or_like('punch_sub_no', $q);
	$this->db->or_like('punch_discipline_no', $q);
	$this->db->or_like('punch_itemNo', $q);
	$this->db->or_like('punch_desc', $q);
	$this->db->or_like('punch_category', $q);
	$this->db->or_like('originator_ctr', $q);
	$this->db->or_like('originator_cpy', $q);
	$this->db->or_like('originator_date', $q);
	$this->db->or_like('verified_ctr', $q);
	$this->db->or_like('verified_cpy', $q);
	$this->db->or_like('verified_date', $q);
	$this->db->or_like('punch_status', $q);
	$this->db->or_like('punch_date', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Punchlist_model.php */
/* Location: ./application/models/Punchlist_model.php */
/* Please DO NOT modify this information : */
/* Generated by Denzoe Codeigniter CRUD Generator 2019-12-27 09:26:28 */
/* http://AA-soft develover.com */