<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Punchlists_model extends CI_Model
{

    public $table = 'tbl_punchlist';
    public $id = 'id_punch';
    public $desc = 'DESC';
    public $asc = 'ASC';
    


    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->desc);        
        $this->db->where('sub_status', 0);
        $this->db->where('discipline_status', 0);
        $this->db->join('tbl_subs', 'tbl_subs.id_sub = tbl_punchlist.id_subs');
        $this->db->join('tbl_disciplines', 'tbl_disciplines.id_discipline = tbl_punchlist.id_disciplines');
        $this->db->join('tbl_equipments', 'tbl_equipments.id_equipment = tbl_punchlist.id_equipments');
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        $this->db->where('sub_status', 0);
        $this->db->where('discipline_status', 0);
        $this->db->join('tbl_subs', 'tbl_subs.id_sub = tbl_punchlist.id_subs');
        $this->db->join('tbl_disciplines', 'tbl_disciplines.id_discipline = tbl_punchlist.id_disciplines');
        $this->db->join('tbl_equipments', 'tbl_equipments.id_equipment = tbl_punchlist.id_equipments');
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->group_start();
        $this->db->like('id_punch', $q);
        $this->db->or_like('punch_id', $q);
        $this->db->or_like('id_locations', $q);
        $this->db->or_like('sub_name', $q);
        $this->db->or_like('discipline_name', $q);
        $this->db->or_like('equipment_no', $q);
        $this->db->or_like('punch_desc', $q);
        $this->db->or_like('punch_category', $q);
        $this->db->or_like('originator_ctr', $q);
        $this->db->or_like('originator_cpy', $q);
        $this->db->or_like('originator_date', $q);
        $this->db->or_like('verified_ctr', $q);
        $this->db->or_like('verified_cpy', $q);
        $this->db->or_like('verified_date', $q);
        $this->db->or_like('punch_status', $q);
        $this->db->or_like('punch_date', $q);
        $this->db->group_end();
        $this->db->where('sub_status', 0);
        $this->db->where('discipline_status', 0);
        $this->db->join('tbl_subs', 'tbl_subs.id_sub = tbl_punchlist.id_subs');
        $this->db->join('tbl_disciplines', 'tbl_disciplines.id_discipline = tbl_punchlist.id_disciplines');
        $this->db->join('tbl_equipments', 'tbl_equipments.id_equipment = tbl_punchlist.id_equipments');
    	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->desc);
        $this->db->group_start();
        $this->db->like('id_punch', $q);
        $this->db->or_like('punch_id', $q);
        $this->db->or_like('id_locations', $q);
        $this->db->or_like('sub_name', $q);
        $this->db->or_like('discipline_name', $q);
        $this->db->or_like('equipment_no', $q);
        $this->db->or_like('punch_desc', $q);
        $this->db->or_like('punch_category', $q);
        $this->db->or_like('originator_ctr', $q);
        $this->db->or_like('originator_cpy', $q);
        $this->db->or_like('originator_date', $q);
        $this->db->or_like('verified_ctr', $q);
        $this->db->or_like('verified_cpy', $q);
        $this->db->or_like('verified_date', $q);
        $this->db->or_like('punch_status', $q);
        $this->db->or_like('punch_date', $q);
        $this->db->group_end();
        $this->db->where('sub_status', 0);
        $this->db->where('discipline_status', 0);
        $this->db->join('tbl_subs', 'tbl_subs.id_sub = tbl_punchlist.id_subs');
        $this->db->join('tbl_disciplines', 'tbl_disciplines.id_discipline = tbl_punchlist.id_disciplines');
        $this->db->join('tbl_equipments', 'tbl_equipments.id_equipment = tbl_punchlist.id_equipments');
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Punchlists_model.php */
/* Location: ./application/models/Punchlists_model.php */
/* Please DO NOT modify this information : */
/* Generated by Denzoe Codeigniter CRUD Generator 2020-01-23 06:31:00 */
/* http://AA-soft develover.com */