<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Systems_model extends CI_Model
{

    public $table = 'tbl_systems';
    public $id = 'id';
    public $desc = 'DESC';
    public $asc = 'ASC';
    


    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all($status = NULL)
    {
        $this->db->order_by($this->id, $this->desc);
        $this->db->select(''.$this->table.'.*,tbl_projects.project_name,tbl_projects.project_status');
        $this->db->where(''.$this->table.'.system_status', $status);
        $this->db->where('tbl_projects.project_status', $status);
        $this->db->from($this->table);
        $this->db->join('tbl_projects', ''.$this->table.'.system_project_no = tbl_projects.id');
        return $this->db->get()->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL, $status = NULL) {
    $this->db->group_start();
    $this->db->like(''.$this->table.'.id', $q);
	$this->db->or_like(''.$this->table.'.system_project_no', $q);
    $this->db->or_like('tbl_projects.project_name', $q);
	$this->db->or_like(''.$this->table.'.system_id', $q);
	$this->db->or_like(''.$this->table.'.system_name', $q);
    $this->db->group_end();
    $this->db->select(''.$this->table.'.*,tbl_projects.project_name,tbl_projects.project_status');
    $this->db->where(''.$this->table.'.system_status', $status);
    $this->db->where('tbl_projects.project_status', $status);
	$this->db->from($this->table);
    $this->db->join('tbl_projects', ''.$this->table.'.system_project_no = tbl_projects.id');
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL, $status = NULL) {
    $this->db->order_by($this->id, $this->desc);
    $this->db->group_start();
    $this->db->like(''.$this->table.'.id', $q);
    $this->db->or_like(''.$this->table.'.system_project_no', $q);
    $this->db->or_like('tbl_projects.project_name', $q);
    $this->db->or_like(''.$this->table.'.system_id', $q);
    $this->db->or_like(''.$this->table.'.system_name', $q);
    $this->db->group_end();
    $this->db->select(''.$this->table.'.*,tbl_projects.project_name,tbl_projects.project_status');
    $this->db->where(''.$this->table.'.system_status', $status);
    $this->db->where('tbl_projects.project_status', $status);
    $this->db->from($this->table);
    $this->db->join('tbl_projects', ''.$this->table.'.system_project_no = tbl_projects.id');
	$this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $data = array('system_status' =>1,);
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

}

/* End of file Systems_model.php */
/* Location: ./application/models/Systems_model.php */
/* Please DO NOT modify this information : */
/* Generated by Denzoe Codeigniter CRUD Generator 2019-12-27 10:59:21 */
/* http://AA-soft develover.com */