<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Templates_model_ extends CI_Model
{

    public $table = 'tbl_templates';
    public $id = 'id_template';
    public $desc = 'DESC';
    public $asc = 'ASC';
    


    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->desc);
        $this->db->where('tbl_disciplines.discipline_status', 0);
        $this->db->join('tbl_disciplines', 'tbl_templates.id_disciplines = tbl_disciplines.id_discipline');
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        $this->db->where('tbl_disciplines.discipline_status', 0);
        $this->db->join('tbl_disciplines', 'tbl_templates.id_disciplines = tbl_disciplines.id_discipline');
        return $this->db->get($this->table)->row();
    }

    // get data detailtemplate by id
    function get_detailtemplate_by_id($id)
    {
        $this->db->where('id_templates', $id);
        return $this->db->get('tbl_template_details')->result();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->group_start();
        $this->db->like('id_template', $q);
    	$this->db->or_like('template_id', $q);
    	$this->db->or_like('template_name', $q);
    	$this->db->or_like('template_type', $q);
    	$this->db->or_like('id_disciplines', $q);
    	$this->db->or_like('template_title_1', $q);
    	$this->db->or_like('template_title_2', $q);
    	$this->db->or_like('template_title_3', $q);
        $this->db->group_end();
        $this->db->where('tbl_disciplines.discipline_status', 0);
        $this->db->join('tbl_disciplines', 'tbl_templates.id_disciplines = tbl_disciplines.id_discipline');
    	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->desc);
        $this->db->group_start();
        $this->db->like('id_template', $q);
        $this->db->or_like('template_id', $q);
        $this->db->or_like('template_name', $q);
        $this->db->or_like('template_type', $q);
        $this->db->or_like('id_disciplines', $q);
        $this->db->or_like('template_title_1', $q);
        $this->db->or_like('template_title_2', $q);
        $this->db->or_like('template_title_3', $q);
        $this->db->group_end();
        $this->db->where('tbl_disciplines.discipline_status', 0);
        $this->db->join('tbl_disciplines', 'tbl_templates.id_disciplines = tbl_disciplines.id_discipline');
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {   $this->db->insert($this->table, $data);
        $id_template = $this->db->insert_id();
        return $id_template;
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        return $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // delete detail data 
    function delete_detail($id)
    {
        $this->db->where('id_template_detail', $id);
        return $this->db->delete('tbl_template_details');
    }

    function insert_detail($data)
    {

        return $this->db->insert_batch('tbl_template_details', $data);
    }

    function update_detail($id, $data)
    {

        return $this->db->update_batch('tbl_template_details', $data, 'id_template_detail');
    }

}

/* End of file Templates_model_.php */
/* Location: ./application/models/Templates_model_.php */
/* Please DO NOT modify this information : */
/* Generated by Denzoe Codeigniter CRUD Generator 2020-01-17 16:07:53 */
/* http://AA-soft develover.com */