<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Templates_model extends CI_Model
{

    public $table = 'tbl_templates';
    public $id = 'id';
    public $desc = 'DESC';
    public $asc = 'ASC';
    


    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->desc);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('tmp_no', $q);
	$this->db->or_like('tmp_id', $q);
	$this->db->or_like('tmp_discipline_no', $q);
	$this->db->or_like('tmp_name', $q);
	$this->db->or_like('tmp_name2', $q);
	$this->db->or_like('tmp_type', $q);
	$this->db->or_like('tmp_type2', $q);
	$this->db->or_like('tmp_title1', $q);
	$this->db->or_like('tmp_title2', $q);
	$this->db->or_like('tmp_title3', $q);
	$this->db->or_like('tmp_title4', $q);
	$this->db->or_like('tmp_remark', $q);
	$this->db->or_like('tmp_status', $q);
	$this->db->or_like('tmp_na', $q);
	$this->db->or_like('tmp_ref', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->desc);
        $this->db->like('id', $q);
	$this->db->or_like('tmp_no', $q);
	$this->db->or_like('tmp_id', $q);
	$this->db->or_like('tmp_discipline_no', $q);
	$this->db->or_like('tmp_name', $q);
	$this->db->or_like('tmp_name2', $q);
	$this->db->or_like('tmp_type', $q);
	$this->db->or_like('tmp_type2', $q);
	$this->db->or_like('tmp_title1', $q);
	$this->db->or_like('tmp_title2', $q);
	$this->db->or_like('tmp_title3', $q);
	$this->db->or_like('tmp_title4', $q);
	$this->db->or_like('tmp_remark', $q);
	$this->db->or_like('tmp_status', $q);
	$this->db->or_like('tmp_na', $q);
	$this->db->or_like('tmp_ref', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Templates_model.php */
/* Location: ./application/models/Templates_model.php */
/* Please DO NOT modify this information : */
/* Generated by Denzoe Codeigniter CRUD Generator 2019-12-28 08:00:53 */
/* http://AA-soft develover.com */